apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultPolicy
metadata:
  name: example-policy
spec:
  name: example
  rules:
    - path: secret/data/example
      capabilities:
        - read
    - path: secret/data/huhu
      capabilities:
        - update
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultAuthEngine
metadata:
  name: example
spec:
  path: cert
  type: cert
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultSecretEngine
metadata:
  name: example
spec:
  path: example
  type: pki
  config:
    maxLeaseTtl: 87600h
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultSecretEngine
metadata:
  name: example-intermediate
spec:
  path: example_intermediate
  type: pki
  config:
    maxLeaseTtl: 26280h
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultRootCertificate
metadata:
  name: example-root
spec:
  path: example
  generate:
    type: internal
    commonName: "example Root CA"
    ttl: 26280h
    keyBits: 4096
    excludeCnFromSans: true
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultIntermediateCertificate
metadata:
  name: example-intermediate
spec:
  path: example_intermediate
  root: "example"
  generate:
    type: internal
    commonName: "example Intermediate CA"
    ttl: 26280h
    keyBits: 4096
    excludeCnFromSans: true
  signing:
    commonName: "example Intermediate CA"
    ttl: 87600h
  roles:
    - name: examplerole
      keyBits: 2048
      maxTtl: 8760h
      allowAnyName: true
    - name: examplerole2
      keyBits: 2048
      maxTtl: 8760h
      allowAnyName: true
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultCertificate
metadata:
  name: example-cert
spec:
  path: example_intermediate
  secretName: testcert
  auth:
    accessorPath: cert
  generate:
    role: examplerole
    commonName: cert.example.com
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultEntity
metadata:
  name: example-entity
spec:
  name: example
  metadata:
    clientId: OWP
    roles: ADMIN
  policies:
    - ops
  aliases:
    - name: cert
      accessorPath: cert
      metadata:
        test: huhu
---
apiVersion: vault.operators.onewealthplace.com/v1
kind: VaultSecret
metadata:
  name: example-secret
spec:
  path: toto/huhu
  content:
    value: |
      Hello this is a cool secret